/*
 * This file is automatically generated; any changes will be lost. 
 */

#nullable enable
#pragma warning disable

using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using NTangle.Services;
using System;
using SqlServerDemo.Publisher.Data;

namespace SqlServerDemo.Publisher.Services
{
    /// <summary>
    /// Provides the Change Data Capture (CDC) <see cref="CustomerCdc"/> entity (aggregate root) <see cref="HostedService{T}"/> capabilities (database table '[Legacy].[Customer]').
    /// </summary>
    public partial class CustomerHostedService : HostedService<ICustomerCdcOrchestrator>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CustomerHostedService"/> class.
        /// </summary>
        /// <param name="serviceProvider">The <see cref="IServiceProvider"/>.</param>
        /// <param name="config">The <see cref="IConfiguration"/>.</param>
        /// <param name="logger">The <see cref="ILogger"/>.</param>
        public CustomerHostedService(IServiceProvider serviceProvider, ILogger<CustomerHostedService> logger, IConfiguration? config = null) : base(serviceProvider, logger, config) { }
    }
}

#pragma warning restore
#nullable restore