/*
 * This file is automatically generated; any changes will be lost. 
 */

#nullable enable
#pragma warning disable

using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using NTangle;
using SqlServerDemo.Publisher.Data;
using SqlServerDemo.Publisher.Services;

namespace SqlServerDemo.Publisher
{
    /// <summary>
    /// Provides <see cref="IServiceCollection"/> extensions.
    /// </summary>
    public static class ServiceCollectionExtensions
    {
        /// <summary>
        /// Adds the generated <see cref="NTangle.Cdc.IEntityOrchestrator"/> services.
        /// </summary>
        /// <param name="services">The <see cref="IServiceCollection"/>.</param>
        /// <returns>The <see cref="IServiceCollection"/>.</returns>
        public static IServiceCollection AddGeneratedOrchestratorServices(this IServiceCollection services)
            => services.AddScoped<IPostCdcOrchestrator, PostCdcOrchestrator>()
                       .AddScoped<IContactCdcOrchestrator, ContactCdcOrchestrator>()
                       .AddScoped<ICustomerCdcOrchestrator, CustomerCdcOrchestrator>();

        /// <summary>
        /// Adds the generated <see cref="NTangle.Services.HostedService"/> services.
        /// </summary>
        /// <param name="services">The <see cref="IServiceCollection"/>.</param>
        /// <returns>The <see cref="IServiceCollection"/>.</returns>
        public static IServiceCollection AddGeneratedHostedServiceServices(this IServiceCollection services, IConfiguration config)
            => services.AddNTangleHostedService<PostHostedService>(config)
                       .AddNTangleHostedService<ContactHostedService>(config)
                       .AddNTangleHostedService<CustomerHostedService>(config);
    }
}

#pragma warning restore
#nullable restore