{{! Copyright (c) Avanade. Licensed under the MIT License. See https://github.com/Avanade/NTangle }}
/*
 * This file is automatically generated; any changes will be lost. 
 */

#nullable enable
#pragma warning disable

using NTangle.Data;
using System.Collections.Generic;
using System.Data;

namespace {{Root.NamespacePublisher}}.Data
{
    /// <summary>
    /// Provides the <see cref="EventOutbox"/> database mapper for table '[{{Root.OutboxSchema}}].[{{Root.OutboxTable}}]'.
    /// </summary>
    public sealed class EventOutboxMapper : EventOutboxMapperBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EventOutboxMapper"/> class.
        /// </summary>
        public EventOutboxMapper() : base("[{{Root.OutboxSchema}}].[udt{{Root.OutboxTable}}List]") { }

        /// <inheritdoc/>
        public override string EnqueueStoredProcedure => "[{{Root.OutboxSchema}}].[{{Root.OutboxEnqueueStoredProcedure}}]";

        /// <inheritdoc/>
        public override string DequeueStoredProcedure => "[{{Root.OutboxSchema}}].[{{Root.OutboxDequeueStoredProcedure}}]";
    }
}

#pragma warning restore
#nullable restore